export const ROUTES = {
  home: "/",
  login: "/login",
  forgotPassword: "/forgot-password",
  verifyCode: "/verify-code",
  setNewPassword: "/set-new-password",
  passwordChanged: "/password-changed",
  dashboard: "/dashboard",
  subscriptions: "/dashboard/subscriptions",
  content: "/dashboard/content",
  aiLifeCoach: "/dashboard/ai-life-coach",
  analytics: "/dashboard/analytics",
  support: "/dashboard/support",
  users: "/dashboard/users",
  products: "/dashboard/products",
  createProduct: "/dashboard/products/create",
  settings: "/dashboard/settings",
} as const;
